import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { accessSync, constants } from "node:fs";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const root = path.resolve(new URL("..", import.meta.url).pathname);
const fixture = fs.mkdtempSync(path.join(os.tmpdir(), "candidates-folder-refactor-"));

try {
  write("src/noisy/api/handler.ts", "export function duplicateThing() { return 1; }\n");
  write("src/noisy/api/route.ts", "export function duplicateThing() { return 2; }\n");
  write("src/noisy/ui/component.tsx", "export const Component = () => null;\n");
  write("src/noisy/model/types.ts", "export type Thing = string;\n");
  write("src/noisy/test/fixture.test.ts", "test('x', () => {});\n");
  write("src/noisy/index.ts", "export { handler } from './api/handler';\n");
  write("src/consumer.ts", "import { duplicateThing } from './noisy/api/handler';\nconsole.log(duplicateThing);\n");
  write("src/simple/index.ts", "export const simple = 1;\n");
  write("pubspec.yaml", "name: fixture_app\n");
  write("lib/main.dart", "void main() {}\n");
  write("lib/app.dart", "class App {}\n");
  write("android/build.gradle", "plugins { id 'com.android.application' version '8.0.0' apply false }\n");
  write("android/app/src/main/AndroidManifest.xml", "<manifest />\n");
  write("android/app/src/main/kotlin/com/example/MainActivity.kt", "class MainActivity\n");
  write("android/gradle.properties", "org.gradle.jvmargs=-Xmx1536M\n");
  write("src/domain/external/client.dart", "class ExternalClient {}\n");
  write("artifacts/run/a.log", "log\n");
  write("artifacts/run/b.log", "log\n");
  write("artifacts/run/result.csv", "x,y\n");
  write("artifacts/run/trace.pid", "123\n");
  write("deploy/raspberry/tests/__pycache__/test_fixture.cpython-312.pyc", "bytecode\n");
  write("deploy/raspberry/tests/test_provision.py", "def test_ok():\n    assert True\n");
  write("src/generated/client/a.go", "// Code generated by test. DO NOT EDIT.\npackage client\n");
  write("src/generated/client/b.go", "// Code generated by test. DO NOT EDIT.\npackage client\n");
  write("src/generated/client/c.go", "// Code generated by test. DO NOT EDIT.\npackage client\n");
  write("opensource/repos/vendor-copy/package-lock.json", "{}\n");
  write("opensource/repos/vendor-copy/blob.bin", "binary\n");
  write("opensource-projects/repo-a/go.mod", "module example.com/repo-a\n");
  write("opensource-projects/repo-a/main.go", "package main\nfunc main() {}\n");
  write("opensource-projects/repo-a/.git", "gitdir: ../.git/modules/repo-a\n");
  write("src/ignored-refactor/a.ts", "export const ignoredA = 1;\n");
  write("src/ignored-refactor/b.ts", "export const ignoredB = 2;\n");
  write("src/ignored-refactor/c.ts", "export const ignoredC = 3;\n");
  write("gitignored-artifacts/a.go", "package ignored\n");
  write("gitignored-artifacts/b.go", "package ignored\n");
  write("gitignored-artifacts/c.go", "package ignored\n");
  write(".gitignore", "gitignored-artifacts/\n*.pyc\n");
  write(".refactorignore", "# scanner ignore rules\nsrc/ignored-refactor/\n");
  write("node_modules/ignored/many.ts", "ignored\n");
  initGitFixture();
  write("src/noisy/api/handler.ts", "export function duplicateThing() { return 3; }\n");
  git("add", "src/noisy/api/handler.ts");
  git("commit", "-m", "touch noisy handler");

  const autoScript = path.join(root, "skills/candidates-folder-refactor/scripts/auto-folder-refactor.sh");
  const autoInstaller = path.join(root, "skills/candidates-folder-refactor/scripts/install.sh");
  accessSync(autoScript, constants.X_OK);
  accessSync(autoInstaller, constants.X_OK);
  const autoHelp = execFileSync(autoScript, ["--help"], { cwd: fixture, encoding: "utf8" });
  assert.match(autoHelp, /auto-folder-refactor\.sh <loops> \[scan-root\]/);
  assert.match(autoHelp, /PI_AUTO_FOLDER_REFACTOR_PI_ARGS/);
  assert.throws(() => execFileSync(autoScript, ["1", ".."], { cwd: fixture, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }), /scan-root must be pwd or a subfolder of pwd/);
  const outside = fs.mkdtempSync(path.join(os.tmpdir(), "outside-auto-folder-refactor-"));
  fs.symlinkSync(outside, path.join(fixture, "outside-link"), "dir");
  assert.throws(() => execFileSync(autoScript, ["1", "outside-link"], { cwd: fixture, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }), /scan-root must be pwd or a subfolder of pwd/);
  fs.rmSync(path.join(fixture, "outside-link"), { force: true });
  fs.rmSync(outside, { recursive: true, force: true });
  const installBin = fs.mkdtempSync(path.join(os.tmpdir(), "auto-folder-refactor-bin-"));
  const installOutput = execFileSync("sh", [autoInstaller], {
    cwd: fixture,
    encoding: "utf8",
    env: { ...process.env, AUTO_FOLDER_REFACTOR_BIN_DIR: installBin },
  });
  assert.match(installOutput, /installed wrapper:/);
  assert.match(installOutput, /example: auto-folder-refactor 10/);
  const installedAuto = path.join(installBin, "auto-folder-refactor");
  accessSync(installedAuto, constants.X_OK);
  const installedHelp = execFileSync(installedAuto, ["--help"], { cwd: fixture, encoding: "utf8" });
  assert.match(installedHelp, /auto-folder-refactor\.sh <loops> \[scan-root\]/);

  const ignoreFixture = fs.mkdtempSync(path.join(os.tmpdir(), "auto-folder-refactor-ignore-"));
  fs.mkdirSync(path.join(ignoreFixture, "artifacts/run"), { recursive: true });
  fs.writeFileSync(path.join(ignoreFixture, "artifacts/run/a.log"), "log\n");
  fs.writeFileSync(path.join(ignoreFixture, "artifacts/run/result.csv"), "x,y\n");
  const ignoreOutput = execFileSync(autoScript, ["ignore"], { cwd: ignoreFixture, encoding: "utf8", env: { ...process.env, NO_COLOR: "1" }, stdio: ["ignore", "pipe", "pipe"] });
  assert.equal(ignoreOutput, "");
  assert.match(fs.readFileSync(path.join(ignoreFixture, ".refactorignore"), "utf8"), /artifacts\//);
  fs.rmSync(ignoreFixture, { recursive: true, force: true });

  const ignoredAddFixture = fs.mkdtempSync(path.join(os.tmpdir(), "auto-folder-refactor-ignored-add-"));
  fs.writeFileSync(path.join(ignoredAddFixture, ".gitignore"), ".pi/\n.understand-anything/\n");
  fs.mkdirSync(path.join(ignoredAddFixture, "src/noisy"), { recursive: true });
  fs.writeFileSync(path.join(ignoredAddFixture, "src/noisy/index.ts"), "export const initial = 1;\n");
  execFileSync("git", ["init"], { cwd: ignoredAddFixture, stdio: "ignore" });
  execFileSync("git", ["config", "user.email", "test@example.invalid"], { cwd: ignoredAddFixture, stdio: "ignore" });
  execFileSync("git", ["config", "user.name", "Test User"], { cwd: ignoredAddFixture, stdio: "ignore" });
  execFileSync("git", ["add", ".gitignore", "src/noisy/index.ts"], { cwd: ignoredAddFixture, stdio: "ignore" });
  execFileSync("git", ["commit", "-m", "initial fixture"], { cwd: ignoredAddFixture, stdio: "ignore" });
  fs.mkdirSync(path.join(ignoredAddFixture, ".pi/logs"), { recursive: true });
  fs.mkdirSync(path.join(ignoredAddFixture, ".understand-anything"), { recursive: true });
  fs.writeFileSync(path.join(ignoredAddFixture, ".pi/logs/local.jsonl"), "{}\n");
  fs.writeFileSync(path.join(ignoredAddFixture, ".understand-anything/meta.json"), "{}\n");
  fs.writeFileSync(path.join(ignoredAddFixture, "src/noisy/index.ts"), "export const changed = 1;\n");
  const ignoredAddFakePi = path.join(os.tmpdir(), `fake-pi-ignored-add-${process.pid}.sh`);
  fs.writeFileSync(ignoredAddFakePi, "#!/usr/bin/env bash\necho ignored add fake pi\n");
  fs.chmodSync(ignoredAddFakePi, 0o755);
  const ignoredAddOutput = execFileSync(autoScript, ["1", "src"], { cwd: ignoredAddFixture, encoding: "utf8", env: { ...process.env, PI_AUTO_FOLDER_REFACTOR_PI: ignoredAddFakePi, PI_AUTO_FOLDER_REFACTOR_NO_PRECOMMIT: "0", PI_AUTO_FOLDER_REFACTOR_DELIVERY: "local", NO_COLOR: "1" }, stdio: ["ignore", "pipe", "pipe"] });
  assert.doesNotMatch(ignoredAddOutput, /The following paths are ignored/);
  assert.doesNotMatch(execFileSync("git", ["show", "--name-only", "--pretty=", "HEAD"], { cwd: ignoredAddFixture, encoding: "utf8" }), /^\.pi\//m);
  fs.rmSync(ignoredAddFakePi, { force: true });
  fs.rmSync(ignoredAddFixture, { recursive: true, force: true });

  const fakePi = path.join(os.tmpdir(), `fake-pi-${process.pid}.sh`);
  fs.writeFileSync(fakePi, "#!/usr/bin/env bash\necho fake pi noop\n");
  fs.chmodSync(fakePi, 0o755);
  const noopOutput = execFileSync(autoScript, ["2", "src"], { cwd: fixture, encoding: "utf8", env: { ...process.env, PI_AUTO_FOLDER_REFACTOR_PI: fakePi, PI_AUTO_FOLDER_REFACTOR_SHOW_PI_OUTPUT: "all" }, stdio: ["ignore", "pipe", "pipe"] });
  assert.match(noopOutput, /fake pi noop/);
  fs.rmSync(path.join(fixture, ".pi/auto-folder-refactor-state"), { recursive: true, force: true });

  fs.rmSync(fakePi, { force: true });
  const fakePiChange = path.join(os.tmpdir(), `fake-pi-change-${process.pid}.sh`);
  fs.writeFileSync(fakePiChange, "#!/usr/bin/env bash\necho fake pi changed\necho changed > src/noisy/auto_refactor_marker.txt\n");
  fs.chmodSync(fakePiChange, 0o755);
  const changeOutput = execFileSync(autoScript, ["1", "src"], { cwd: fixture, encoding: "utf8", env: { ...process.env, PI_AUTO_FOLDER_REFACTOR_PI: fakePiChange, PI_AUTO_FOLDER_REFACTOR_SHOW_PI_OUTPUT: "all", PI_AUTO_FOLDER_REFACTOR_REQUIRE_PROGRESS: "0", PI_AUTO_FOLDER_REFACTOR_DELIVERY: "local", NO_COLOR: "1" }, stdio: ["ignore", "pipe", "pipe"] });
  assert.match(changeOutput, /fake pi changed/);
  assert.match(git("log", "-1", "--pretty=%s"), /Refactor src\/noisy topology/);
  assert.equal(git("status", "--porcelain", "--", "src/noisy/auto_refactor_marker.txt"), "");
  fs.rmSync(fakePiChange, { force: true });

  const fakePiBadDiff = path.join(os.tmpdir(), `fake-pi-bad-diff-${process.pid}.sh`);
  fs.writeFileSync(fakePiBadDiff, "#!/usr/bin/env bash\necho fake pi bad diff\nprintf 'bad trailing whitespace  \\n' >> src/noisy/index.ts\n");
  fs.chmodSync(fakePiBadDiff, 0o755);
  const badDiffOutput = execFileSync(autoScript, ["1", "src"], { cwd: fixture, encoding: "utf8", env: { ...process.env, PI_AUTO_FOLDER_REFACTOR_PI: fakePiBadDiff, PI_AUTO_FOLDER_REFACTOR_DELIVERY: "local", NO_COLOR: "1" }, stdio: ["ignore", "pipe", "pipe"] });
  assert.match(badDiffOutput, /trailing whitespace/);
  assert.equal(git("status", "--porcelain", "--", "src/noisy/index.ts"), "");
  fs.rmSync(fakePiBadDiff, { force: true });
  fs.rmSync(path.join(fixture, ".pi/auto-folder-refactor-state"), { recursive: true, force: true });

  const fakePiTimeout = path.join(os.tmpdir(), `fake-pi-timeout-${process.pid}.sh`);
  fs.writeFileSync(fakePiTimeout, "#!/usr/bin/env bash\necho fake pi timeout\necho partial > src/noisy/partial_timeout.txt\nsleep 5\n");
  fs.chmodSync(fakePiTimeout, 0o755);
  const timeoutOutput = execFileSync(autoScript, ["1", "src"], { cwd: fixture, encoding: "utf8", env: { ...process.env, PI_AUTO_FOLDER_REFACTOR_PI: fakePiTimeout, PI_AUTO_FOLDER_REFACTOR_TIMEOUT_SECONDS: "1", PI_AUTO_FOLDER_REFACTOR_DELIVERY: "local", NO_COLOR: "1" }, stdio: ["ignore", "pipe", "pipe"] });
  assert.match(timeoutOutput, /fake pi timeout/);
  assert.equal(fs.existsSync(path.join(fixture, "src/noisy/partial_timeout.txt")), false);
  fs.rmSync(fakePiTimeout, { force: true });
  fs.rmSync(path.join(fixture, ".pi/auto-folder-refactor-state"), { recursive: true, force: true });

  const fakePiNoMetric = path.join(os.tmpdir(), `fake-pi-no-metric-${process.pid}.sh`);
  fs.writeFileSync(fakePiNoMetric, "#!/usr/bin/env bash\necho fake pi no metric\necho marker > src/noisy/no_metric_marker.txt\n");
  fs.chmodSync(fakePiNoMetric, 0o755);
  execFileSync(autoScript, ["1", "src"], { cwd: fixture, encoding: "utf8", env: { ...process.env, PI_AUTO_FOLDER_REFACTOR_PI: fakePiNoMetric, PI_AUTO_FOLDER_REFACTOR_DELIVERY: "local", PI_AUTO_FOLDER_REFACTOR_COOLDOWN_SECONDS: "0", NO_COLOR: "1" }, stdio: ["ignore", "pipe", "pipe"] });
  assert.equal(fs.existsSync(path.join(fixture, "src/noisy/no_metric_marker.txt")), false);
  const skipStateDir = path.join(fixture, ".pi/auto-folder-refactor-state");
  const stateText = fs.readdirSync(skipStateDir).filter((name) => name.startsWith("state.") && name.endsWith(".jsonl")).map((name) => fs.readFileSync(path.join(skipStateDir, name), "utf8")).join("\n");
  assert.match(stateText, /"state":"cooldown"/);
  assert.match(stateText, /"reason":"no metric progress rollback"/);
  execFileSync(autoScript, ["1", "src"], { cwd: fixture, encoding: "utf8", env: { ...process.env, PI_AUTO_FOLDER_REFACTOR_PI: fakePiNoMetric, PI_AUTO_FOLDER_REFACTOR_DELIVERY: "local", PI_AUTO_FOLDER_REFACTOR_COOLDOWN_SECONDS: "1", PI_AUTO_FOLDER_REFACTOR_COOLDOWN_MAX_SECONDS: "4", NO_COLOR: "1" }, stdio: ["ignore", "pipe", "pipe"] });
  const updatedStateText = fs.readdirSync(skipStateDir).filter((name) => name.startsWith("state.") && name.endsWith(".jsonl")).map((name) => fs.readFileSync(path.join(skipStateDir, name), "utf8")).join("\n");
  assert.equal((updatedStateText.match(/"state":"cooldown"/g) || []).length, 2);
  fs.rmSync(fakePiNoMetric, { force: true });
  fs.rmSync(skipStateDir, { recursive: true, force: true });

  const fakePiBugfind = path.join(os.tmpdir(), `fake-pi-bugfind-${process.pid}.sh`);
  fs.writeFileSync(fakePiBugfind, "#!/usr/bin/env bash\necho fake pi bugfind\necho fixed > src/noisy/bugfind_marker.txt\necho runtime > src/noisy/paper-toxicity-decisions.jsonl\n");
  fs.chmodSync(fakePiBugfind, 0o755);
  const bugfindOutput = execFileSync(autoScript, ["1", "src"], { cwd: fixture, encoding: "utf8", env: { ...process.env, PI_AUTO_FOLDER_REFACTOR_PI: fakePiBugfind, PI_AUTO_FOLDER_REFACTOR_BUGFIND_THRESHOLD: "999", PI_AUTO_FOLDER_REFACTOR_DELIVERY: "local", PI_AUTO_FOLDER_REFACTOR_SHOW_PI_OUTPUT: "all", NO_COLOR: "1" }, stdio: ["ignore", "pipe", "pipe"] });
  assert.match(bugfindOutput, /fake pi bugfind/);
  assert.match(git("log", "-1", "--pretty=%s"), /Bugfind 1-1 visibility slice/);
  assert.equal(git("status", "--porcelain", "--", "src/noisy/bugfind_marker.txt"), "");
  assert.equal(fs.existsSync(path.join(fixture, "src/noisy/paper-toxicity-decisions.jsonl")), false);
  fs.rmSync(fakePiBugfind, { force: true });
  fs.rmSync(installBin, { recursive: true, force: true });

  const script = path.join(root, "skills/candidates-folder-refactor/scripts/find-candidates.mjs");
  const repoOutput = execFileSync(process.execPath, [script, "."], { cwd: fixture, encoding: "utf8" });
  assert.match(repoOutput, /src\/noisy/);
  assert.match(repoOutput, /churn [1-9]/);
  assert.match(repoOutput, /callers [1-9]/);
  assert.match(repoOutput, /tests 1/);
  assert.match(repoOutput, /duplicates [1-9]/);
  assert.doesNotMatch(repoOutput, /node_modules/);
  assert.doesNotMatch(repoOutput, /ignored-refactor/);
  assert.doesNotMatch(repoOutput, /gitignored-artifacts/);
  assert.doesNotMatch(repoOutput.split("1. ")[1] || "", /__pycache__/);
  assert.match(repoOutput, /Suggested \.refactorignore entries:/);
  assert.match(repoOutput, /artifacts\//);
  assert.match(repoOutput, /src\/generated\//);
  assert.match(repoOutput, /opensource\/repos\//);
  assert.match(repoOutput, /android\//);
  assert.match(repoOutput, /opensource-projects\/repo-a\//);
  assert.match(repoOutput, /confidence [3-9]/);
  assert.doesNotMatch(repoOutput.split("Log:")[0], /\d+\. artifacts/);
  assert.doesNotMatch(repoOutput.split("Log:")[0], /\d+\. src\/generated/);
  assert.match(repoOutput, /Log: .*\.pi\/candidates-folder-refactor\/latest\.json/);
  assert.equal(fs.existsSync(path.join(fixture, ".pi/candidates-folder-refactor/latest.json")), true);
  assert.equal(fs.existsSync(path.join(fixture, ".pi/candidates-folder-refactor/runs.jsonl")), true);
  const latestReport = JSON.parse(fs.readFileSync(path.join(fixture, ".pi/candidates-folder-refactor/latest.json"), "utf8"));
  assert.equal(latestReport.refactorIgnoreSuggestions.some((item) => item.pattern === "artifacts/"), true);
  assert.equal(latestReport.refactorIgnoreSuggestions.some((item) => item.pattern === "src/generated/"), true);
  assert.equal(latestReport.refactorIgnoreSuggestions.some((item) => item.pattern === "opensource/repos/"), true);
  assert.equal(latestReport.refactorIgnoreSuggestions.some((item) => item.pattern === "android/"), true);
  assert.equal(latestReport.refactorIgnoreSuggestions.some((item) => item.pattern === "opensource-projects/repo-a/"), true);
  assert.equal(latestReport.refactorIgnoreSuggestions.some((item) => item.pattern === "opensource/"), false);
  assert.equal(latestReport.candidates.some((item) => item.relative === "src/generated"), false);
  assert.equal(latestReport.candidates.some((item) => item.relative === "src/generated/client"), false);
  assert.equal(latestReport.candidates.some((item) => item.relative === "android"), false);
  assert.equal(latestReport.candidates.some((item) => item.relative.includes("__pycache__")), false);
  assert.equal(latestReport.candidates.some((item) => item.relative === "gitignored-artifacts"), false);
  assert.equal(latestReport.refactorIgnoreSuggestions.some((item) => item.pattern === "gitignored-artifacts/"), false);
  assert.equal(latestReport.refactorIgnoreSuggestions.some((item) => item.pattern === "lib/"), false);
  assert.equal(latestReport.refactorIgnoreSuggestions.some((item) => item.pattern === "src/domain/external/"), false);
  const cachedOutput = execFileSync(process.execPath, [script, ".", "--from-log"], { cwd: fixture, encoding: "utf8" });
  assert.match(cachedOutput, /From log:/);
  assert.match(cachedOutput, /src\/noisy/);

  const folderOutput = execFileSync(process.execPath, [script, "src"], { cwd: fixture, encoding: "utf8" });
  assert.match(folderOutput, /src\/noisy/);
  assert.doesNotMatch(folderOutput.split("\n").slice(1).join("\n"), /\.\.\/src/);
} finally {
  fs.rmSync(fixture, { recursive: true, force: true });
}

console.log("candidates-folder-refactor ok");

function write(relativePath, content) {
  const file = path.join(fixture, relativePath);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function initGitFixture() {
  git("init");
  git("config", "user.email", "test@example.invalid");
  git("config", "user.name", "Test User");
  git("add", ".");
  git("commit", "-m", "initial fixture");
}

function git(...args) {
  return execFileSync("git", args, { cwd: fixture, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
}
