import assert from "node:assert/strict";
import { execFile as execFileCallback } from "node:child_process";
import { mkdtemp, mkdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import registerFolderRefactorExtension from "../extensions/folder-refactor/index.js";
import {
  auditFolderRefactorCompletion,
  buildFolderRefactorPrompt,
  formatAuditResult,
  readFolderRefactorState,
  scanFolderRefactorTarget,
  stableStringify,
  writeFolderRefactorState,
} from "../lib/folder-refactor/guardrail.js";

const execFile = promisify(execFileCallback);
const git = (cwd, args) => execFile("git", args, { cwd });

const fixture = await mkdtemp(join(tmpdir(), "folder-refactor-extension-"));
try {
  await mkdir(join(fixture, "internal", "config", "auth"), { recursive: true });
  await writeFile(join(fixture, "go.mod"), "module example.com/project\n");
  await writeFile(join(fixture, ".gitignore"), "*.log\n");
  await writeFile(join(fixture, "internal", "config", "auth", "auth.go"), "package auth\n\nfunc Check() {}\n");
  await writeFile(join(fixture, "internal", "config", "config.go"), "package config\n");
  await writeFile(join(fixture, "internal", "config", "slash_title.go"), "package config\n");
  await writeFile(join(fixture, "internal", "config", "schema_test.go"), "package config\n");
  await writeFile(join(fixture, "internal", "config", "setup.test.mjs"), "import \"./config.js\";\n");

  const scan = await scanFolderRefactorTarget(fixture, "internal/config");
  assert.deepEqual(scan.rootFiles, ["config.go", "schema_test.go", "setup.test.mjs", "slash_title.go"]);
  assert.deepEqual(scan.rootDirs, ["auth"]);
  await assert.rejects(
    () => scanFolderRefactorTarget(fixture, "internal/missing"),
    /folder-refactor target must be an existing directory: internal\/missing/,
  );
  await assert.rejects(
    () => scanFolderRefactorTarget(fixture, "internal/config/config.go"),
    /folder-refactor target must be an existing directory: internal\/config\/config.go/,
  );
  await assert.rejects(
    () => scanFolderRefactorTarget(fixture, join(tmpdir(), `folder-refactor-outside-${process.pid}`)),
    /folder-refactor target must be inside cwd/,
  );
  const outside = await mkdtemp(join(tmpdir(), "folder-refactor-outside-real-"));
  await writeFile(join(outside, "outside.go"), "package outside\n");
  await symlink(outside, join(fixture, "outside-link"), "dir");
  await assert.rejects(
    () => scanFolderRefactorTarget(fixture, "outside-link"),
    /folder-refactor target must be inside cwd/,
  );
  await rm(outside, { recursive: true, force: true });

  const failingAudit = auditFolderRefactorCompletion(scan, {
    plannedTopologyComplete: true,
    facadeFiles: ["config.go"],
    outOfScopeFiles: ["schema_test.go", "setup.test.mjs"],
  });
  assert.equal(failingAudit.ok, false);
  assert.deepEqual(failingAudit.unclassified, ["slash_title.go"]);
  assert.match(formatAuditResult(failingAudit), /FOLDER_REFACTOR_AUDIT: fail/);

  const passingAudit = auditFolderRefactorCompletion(scan, {
    plannedTopologyComplete: false,
    facadeFiles: ["config.go"],
    outOfScopeFiles: ["schema_test.go", "setup.test.mjs"],
    nextCandidateFiles: ["slash_title.go"],
  });
  assert.equal(passingAudit.ok, true);
  assert.match(formatAuditResult(passingAudit), /next candidates: slash_title\.go/);

  const prompt = buildFolderRefactorPrompt("internal/config");
  assert.match(prompt, /^\/skill:skill-folder-refactor internal\/config/);
  assert.match(prompt, /folder_refactor_audit/);

  const written = await writeFolderRefactorState(fixture, "internal/config", {
    objective: "split config",
    completedSlices: ["auth"],
    nextCandidates: ["slash_title.go"],
    validationReceipts: ["go test ./internal/config/..."],
  });
  const read = await readFolderRefactorState(fixture, "internal/config");
  assert.equal(read.file, written.file);
  assert.equal(read.payload.objective, "split config");
  assert.deepEqual(read.payload.nextCandidates, ["slash_title.go"]);

  await git(fixture, ["init"]);
  await git(fixture, ["config", "user.email", "test@example.com"]);
  await git(fixture, ["config", "user.name", "Test User"]);
  await git(fixture, ["add", ".gitignore", "go.mod", "internal"]);
  await git(fixture, ["-c", "commit.gpgsign=false", "commit", "-m", "initial"]);

  await writeFile(
    join(fixture, "internal", "config", "config.go"),
    "package config\n\nimport \"example.com/project/internal/config/auth\"\n\nfunc Load() { auth.Check() }\n",
  );
  await writeFile(join(fixture, "internal", "config", "new_test.go"), "package config\n");
  await writeFile(join(fixture, "internal", "config", "generated.pb.go"), "// Code generated by protoc. DO NOT EDIT.\npackage config\n");
  await writeFile(join(fixture, "internal", "config", "ignored.log"), "ignored\n");

  const richScan = await scanFolderRefactorTarget(fixture, "internal/config", { depth: 2, limit: 3 });
  assert.equal(richScan.depth, 2);
  assert.equal(richScan.truncated, true);
  assert.equal(richScan.entries.length, 3);
  assert.match(richScan.scanHash, /^[a-f0-9]{64}$/);
  assert.equal(stableStringify({ b: 1, a: 2 }, 0), "{\"a\":2,\"b\":1}");

  const rootFilesByName = Object.fromEntries(richScan.files.map((file) => [file.basename, file]));
  assert.equal(rootFilesByName["config.go"].gitStatus, "modified");
  assert.equal(rootFilesByName["schema_test.go"].gitStatus, "clean");
  assert.equal(rootFilesByName["new_test.go"].gitStatus, "untracked");
  assert.equal(rootFilesByName["new_test.go"].isLikelyTest, true);
  assert.equal(rootFilesByName["setup.test.mjs"].isLikelyTest, true);
  assert.deepEqual(rootFilesByName["setup.test.mjs"].localImports, ["./config.js"]);
  assert.equal(rootFilesByName["generated.pb.go"].isGenerated, true);
  assert.equal(rootFilesByName["ignored.log"].gitStatus, "ignored");
  assert.equal(rootFilesByName["config.go"].packageName, "config");
  assert.deepEqual(rootFilesByName["config.go"].localImports, ["example.com/project/internal/config/auth"]);

  const baselineMismatch = auditFolderRefactorCompletion(richScan, {
    baselineHash: "bad-hash",
    facadeFiles: richScan.rootFiles,
  });
  assert.equal(baselineMismatch.ok, false);
  assert.match(formatAuditResult(baselineMismatch), /scan baseline hash mismatch/);

  const registeredCommands = [];
  const registeredTools = [];
  registerFolderRefactorExtension({
    getAllTools: () => [
      { name: "folder_refactor_scan" },
      { name: "folder_refactor_audit" },
      { name: "folder_refactor_state" },
    ],
    on: (_event, handler) => handler(),
    registerCommand: (name) => registeredCommands.push(name),
    registerTool: (definition) => registeredTools.push(definition.name),
  });
  assert.deepEqual(registeredCommands, ["folder-refactor"]);
  assert.deepEqual(registeredTools, []);
} finally {
  await rm(fixture, { recursive: true, force: true });
}

console.log("folder-refactor-extension ok");
